# Generated by Django 4.2.4 on 2023-08-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Title',
            field=models.CharField(max_length=25),
        ),
    ]
